TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.25
  min_vel_x: 0.08

  max_vel_theta:  1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 1.0

  acc_lim_x: 1.0
  acc_lim_y: 0.0
  acc_lim_theta: 0.6

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.10
  yaw_goal_tolerance: 0.05

# Differential-drive robot configuration
  holonomic_robot: false

# Forward Simulation Parameters
  sim_time: 2.0
  vx_samples: 18
  vtheta_samples: 20
  sim_granularity: 0.05

  meter_scoring: true






  path_distance_bias: 2.8  #[working on 8.0]
  occdist_scale: 0.01


