local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  static_map: false
  update_frequency: 5.0
  publish_frequency: 2.5
  transform_tolerance: 0.5 
  width: 5
  height: 5

 
  rolling_window: true

  resolution: 0.05



  
