footprint: [[0.70, 0.65], [0.70, -0.65], [-0.70, -0.65], [-0.75, 0.65]]
observation_sources: laser_scan_sensor
laser_scan_sensor:
 sensor_frame: laser_link
 data_type: LaserScan
 topic: scan
 marking: true
 clearing: true


obstacle_range: 3.0
raytrace_range: 3.5
inflation_radius: 1.0
cost_scaling_factor: 3.0
