global_costmap:
  global_frame: map
  robot_base_frame: base_link

  update_frequency: 1.0
  publish_frequency: 0.5
  transform_tolerance: 0.5

#  plugins:
#- {name: static_layer, type: "costmap_2d::StaticLayer"}
# - {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
#- {name: inflater_layer, type: "costmap_2d::InflationLayer"}


  inflater_layer:
   inflation_radius: 0.2
   cost_scaling_factor: 1.

  static_map: true
